cuda8.0-cudnn7-opencv3.2.0-tensorrt3.0.4:
	nvidia-docker build -t mathpresso/cuda8.0-cudnn7-opencv3.2.0-tensorrt:3.0.4 -f Dockerfile.cuda8.0-cudnn7-opencv3.2.0-tensorrt3.0.4 .

cuda9.0-cudnn7-opencv3.4.1-tensorrt3.0.4:
	nvidia-docker build -t mathpresso/cuda9.0-cudnn7-opencv3.4.1-tensorrt:3.0.4 -f Dockerfile.cuda9.0-cudnn7-opencv3.4.1-tensorrt3.0.4 .
