FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04
# TO: mathpresso/cuda9.0-cudnn7-opencv:3.4.1

# Reference : https://github.com/NVIDIA/gpu-rest-engine/blob/master/Dockerfile.tensorrt_server

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates \
        cmake \
        git \
        libboost-all-dev \
        libgflags-dev \
        libgoogle-glog-dev \
        libprotobuf-dev \
        pkg-config \
        protobuf-compiler \
        python-yaml \
        wget \
        python3.5-dev \
        libpython3.5-dev \
        python3-numpy \
    && rm -rf /var/lib/apt/lists/*

# Install OpenCV 3.4.1
RUN git clone --depth 1 -b 3.4.1 https://github.com/opencv/opencv.git /opencv && \
    git clone --depth 1 -b 3.4.1 https://github.com/opencv/opencv_contrib.git /opencv_contrib && \
    cd /opencv && \
    mkdir build && cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=/usr/local \
          -DBUILD_SHARED_LIBS=ON \
          -DWITH_JPEG=ON -DBUILD_JPEG=ON -DWITH_PNG=ON -DBUILD_PNG=ON \
          -DINSTALL_PYTHON_EXAMPLES=ON \
          -DINSTALL_C_EXAMPLES=OFF \
          -DOPENCV_EXTRA_MODULES_PATH=/opencv_contrib/modules \
          -DBUILD_EXAMPLES=ON .. && \
    make -j"$(nproc)" install && ldconfig && \
    rm -rf /opencv && rm -rf /opencv_contrib

