cuda8.0-cudnn7-opencv3.2.0:
	nvidia-docker build -t mathpresso/cuda8.0-cudnn7-opencv:3.2.0 -f Dockerfile.cuda8.0-cudnn7-opencv3.2.0 .

cuda9.0-cudnn7-opencv3.4.1:
	nvidia-docker build -t mathpresso/cuda9.0-cudnn7-opencv:3.4.1 -f Dockerfile.cuda9.0-cudnn7-opencv3.4.1 .
